# Generated by Django 5.1.3 on 2024-11-24 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0007_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('human_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgiin_ovog', models.CharField(max_length=150)),
                ('ovog', models.CharField(max_length=150)),
                ('ys_undes', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('RD', models.CharField(max_length=100, verbose_name='Регистерийн дугаар')),
                ('birth_date', models.DateField()),
                ('birth_counter', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('эрэгтэй', 'Эрэгтэй'), ('эмэгтэй', 'Эмэгтэй'), ('бусад', 'Бусад')], max_length=100)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
