# Generated by Django 5.1.3 on 2024-11-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0008_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavlah',
            fields=[
                ('lavlah_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nershil', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LavlahEdu',
            fields=[
                ('lavlahEdu_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nershil', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('death_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('death_time', models.DateField()),
                ('shaltgaan', models.TextField(blank=True, null=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='Divorce',
            fields=[
                ('divorce_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('divorce_date', models.DateField()),
                ('shaltgaan', models.TextField(blank=True, null=True)),
                ('divorced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divorced_by', to='ugiinbichig.human')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divorces', to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('health_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('history', models.TextField(blank=True, null=True)),
                ('health_date', models.DateField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='human_image/')),
                ('discription', models.CharField(blank=True, max_length=250, null=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('edu_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
                ('lavlavEdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.lavlahedu')),
            ],
        ),
        migrations.CreateModel(
            name='Marry',
            fields=[
                ('marry_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('marry_date', models.DateField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marries', to='ugiinbichig.human')),
                ('marryd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='married_to', to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='Mergejil',
            fields=[
                ('mergejil_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('mergejil', models.CharField(max_length=250)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('school_name', models.CharField(max_length=250)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
        migrations.CreateModel(
            name='Who',
            fields=[
                ('who_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relarions', to='ugiinbichig.human')),
                ('lavlah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.lavlah')),
                ('relations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='ugiinbichig.human')),
            ],
        ),
    ]
