# Generated by Django 5.1.3 on 2024-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0010_alter_human_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
