# Generated by Django 5.1.3 on 2024-12-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0011_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('shape_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('shape_type', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('human_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
    ]
