# Generated by Django 5.1.3 on 2024-12-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0012_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='human_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human', unique=True),
        ),
    ]
