# Generated by Django 5.1.3 on 2024-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0014_remove_shape_human_id_human_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
