# Generated by Django 5.1.3 on 2024-12-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0015_alter_human_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
