# Generated by Django 5.1.3 on 2024-12-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0016_shape_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape',
            old_name='shape_type',
            new_name='type',
        ),
    ]
