# Generated by Django 5.1.3 on 2024-12-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0017_rename_shape_type_shape_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='shape',
            name='human_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human'),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
