# Generated by Django 5.1.3 on 2025-01-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0018_remove_human_parent_id_shape_human_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
