# Generated by Django 5.1.3 on 2025-01-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0019_user_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='human_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human'),
        ),
    ]
