# Generated by Django 5.1.3 on 2025-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0020_alter_shape_human_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='RD',
            field=models.CharField(max_length=100, unique=True, verbose_name='Регистерийн дугаар'),
        ),
    ]
