# Generated by Django 5.1.3 on 2025-02-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0021_alter_human_rd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='ugiinbichig.human'),
        ),
    ]
