# Generated by Django 5.1.3 on 2025-03-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0022_alter_who_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='lavlah',
            field=models.CharField(max_length=250),
        ),
    ]
