# Generated by Django 5.1.3 on 2025-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0023_alter_who_lavlah'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='zereg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Edu',
        ),
        migrations.DeleteModel(
            name='LavlahEdu',
        ),
    ]
