# Generated by Django 5.1.3 on 2025-03-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0024_school_zereg_delete_edu_delete_lavlahedu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ugiinbichig.human')),
            ],
        ),
        migrations.DeleteModel(
            name='Lavlah',
        ),
    ]
