# Generated by Django 5.1.3 on 2025-03-25 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0025_video_delete_lavlah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shapelist',
            fields=[
                ('shapelist_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('shape', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.shape')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
