# Generated by Django 5.1.3 on 2025-03-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0026_shapelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapelist',
            old_name='user',
            new_name='user_id',
        ),
    ]
