# Generated by Django 5.1.3 on 2025-03-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0027_rename_user_shapelist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapelist',
            old_name='user_id',
            new_name='user',
        ),
    ]
