# Generated by Django 5.1.3 on 2025-03-26 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0028_rename_user_id_shapelist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
