# Generated by Django 5.1.3 on 2025-03-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0029_shape_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shapelist',
        ),
    ]
