# Generated by Django 5.1.3 on 2025-03-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0030_delete_shapelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('Punishment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('punishment_time', models.DateField()),
                ('shaltgaan', models.TextField(blank=True, null=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugiinbichig.human')),
            ],
        ),
    ]
