# Generated by Django 5.1.3 on 2025-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0031_punishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishment',
            name='imprisoned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
