# Generated by Django 5.1.3 on 2025-03-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0032_punishment_imprisoned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishment',
            old_name='Punishment_id',
            new_name='punishment_id',
        ),
    ]
