# Generated by Django 5.1.3 on 2025-03-28 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugiinbichig', '0033_rename_punishment_id_punishment_punishment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('profile', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('human', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='ugiinbichig.human')),
            ],
        ),
    ]
