from .user_model import User
from .human_model import Human
from .death_model import Death
from .divorce_model import Divorce
from .health_model import Health
from .image_model import Image
from .marry_model import Marry
from .relations_model import Who
from .mergejil_model import Mergejil
from .school_model import School
from .shape_model import Shape
from .video_model import Video